# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07f8fecb6b1a46d671d93ff31cfa0a04d2a79d00597643534a01eb4705bbac5c13fba1a539c109ad2bcd5906440c8d4aee3c63c3808b6620e1e0e29907d57c79

test:
  secret_key_base: bb7628a377a616ea2cf38880ac3f49a0785ed0cf77c6e71c58d18bdf96219e27020a0582186cc4df03a403f6ae26b5c98d92c37ed2f53f1ae656d052df84b82b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
